CONFIG_BOOT_SIGNATURE_TYPE_ECDSA_P256=y
CONFIG_BOOT_UPGRADE_ONLY=y
CONFIG_BOOT_VALIDATE_SLOT0=y
CONFIG_BOOT_USB_DFU_GPIO=y
CONFIG_BOOT_USB_DFU_NO_APPLICATION=y
CONFIG_USB_DEVICE_BOS=y
CONFIG_USB_DFU_REBOOT=y
CONFIG_USB_DFU_ENABLE_UPLOAD=n
CONFIG_USB_DFU_PERMANENT_DOWNLOAD=n
CONFIG_USB_DEVICE_VID=0
CONFIG_USB_DEVICE_PID=0
CONFIG_USB_DEVICE_DFU_PID=0
CONFIG_USB_DEVICE_MANUFACTURER="ELROOT"
CONFIG_USB_DEVICE_PRODUCT="ELROOT CANFD (2 channel)"
CONFIG_USB_DEVICE_SN="00000000000000000000000000000000"
CONFIG_USB_REQUEST_BUFFER_SIZE=1024
CONFIG_IMG_ERASE_PROGRESSIVELY=y
CONFIG_PICOLIBC=n
CONFIG_MINIMAL_LIBC=y
CONFIG_MAIN_STACK_SIZE=10240
